baseURL = "https://babybennett.life/"
languageCode = "en-us"
title = "Baby Bennett"
theme = "paper"
[params]
  description = "Updates on the Baby Bennett"
  customStyles = "css/custom.css"
  [author]
    name = "Joshua Bennett"
    homepage = "https://joshuadbennett.com"