baseURL = "https://babybennett.life/"
languageCode = "en-us"
title = "Baby Bennett"
theme = "paper"
description = "Updates on the Baby Bennett"

[author]
  name = "Joshua Bennett"
  homepage = "https://joshuadbennett.com"